//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.09 at 09:59:38 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://soap.ameya.com/student", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ameya.soap.student;
